name: Publish tree-sitter-stack-graphs-typescript release

on:
  push:
    tags:
      - tree-sitter-stack-graphs-typescript-v*

permissions:
  contents: write

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
      CARGO_INCREMENTAL: 0
      CRATE_DIR: './languages/tree-sitter-stack-graphs-typescript'
    steps:
      - name: Install Rust environment
        uses: hecrj/setup-rust-action@110f36749599534ca96628b82f52ae67e5d95a3c # v2
      - name: Checkout repository
        uses: actions/checkout@v4
      # TODO Verify the crate version matches the tag
      - name: Test crate
        run: cargo test --all-features
        working-directory: ${{ env.CRATE_DIR }}
      - name: Verify publish crate
        run: cargo publish --dry-run
        working-directory: ${{ env.CRATE_DIR }}
      - name: Publish crate
        run: cargo publish
        working-directory: ${{ env.CRATE_DIR }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  create-release:
    needs: publish-crate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create GitHub release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1
        with:
          body: |
            Find more info on all releases at https://crates.io/crates/tree-sitter-stack-graphs-typescript.
          token: ${{ secrets.GITHUB_TOKEN }}
